-- ==========================================================
-- ISO 27001:2022 – ANEXO A – 93 CONTROLES
-- Inserción masiva para tabla controles
-- ==========================================================

USE iso_platform;

INSERT INTO controles (codigo, nombre, descripcion, dominio_id) VALUES
-- DOMINIO 5 – Organizacionales (37 controles)
('5.1','Políticas de seguridad de la información','Definir políticas apropiadas para la seguridad de la información',1),
('5.2','Roles y responsabilidades','Establecer roles y responsabilidades en seguridad',1),
('5.3','Segregación de tareas','Separar tareas y áreas de responsabilidad conflictivas',1),
('5.4','Contacto con autoridades','Mantener contacto con autoridades regulatorias',1),
('5.5','Contacto con grupos de interés especial','Mantener contacto con foros, asociaciones de seguridad',1),
('5.6','Seguridad en la gestión de amenazas','Establecer proceso para recibir y gestionar amenazas',1),
('5.7','Gestión de activos','Identificar y gestionar activos de información',1),
('5.8','Clasificación de la información','Clasificar la información según su criticidad',1),
('5.9','Etiquetado y manejo de la información','Etiquetar activos según su clasificación',1),
('5.10','Gestión de accesos','Controlar el acceso a la información y sistemas',1),
('5.11','Política de uso de activos de criptografía','Definir uso aceptable de criptografía',1),
('5.12','Gestión de permisos de acceso','Administrar permisos de forma segura',1),
('5.13','Gestión de la información y otros activos asociados','Gestionar ciclo de vida de activos',1),
('5.14','Transferencia segura de información','Proteger la información en transferencias',1),
('5.15','Control de acceso y sistemas de información','Restringir acceso a sistemas y servicios',1),
('5.16','Gestión de identidades','Gestionar identidades únicas y fiables',1),
('5.17','Información de autenticación','Proteger credenciales y secretos de autenticación',1),
('5.18','Revisión de derechos de acceso','Revisar periódicamente permisos',1),
('5.19','Restricción de acceso y privilegios de usuario','Limitar privilegios al mínimo necesario',1),
('5.20','Registro y monitoreo','Registrar eventos relevantes de seguridad',1),
('5.21','Instalación de software en sistemas operativos','Controlar instalación de software',1),
('5.22','Gestión de vulnerabilidades técnicas','Identificar y gestionar vulnerabilidades',1),
('5.23','Restricciones en el acceso al código de programación','Limitar acceso a código fuente',1),
('5.24','Gestión de incidentes de seguridad','Establecer proceso de gestión de incidentes',1),
('5.25','Responsabilidades y procedimientos de gestión de incidentes','Definir roles en gestión de incidentes',1),
('5.26','Aprendizaje de incidentes de seguridad','Analizar y aprender de incidentes',1),
('5.27','Recopilación de evidencias','Recolectar y proteger evidencias de incidentes',1),
('5.28','Gestión de riesgos','Establecer proceso de gestión de riesgos',1),
('5.29','Evaluación y tratamiento de riesgos','Evaluar y tratar riesgos de seguridad',1),
('5.30','Criterios de aceptación de riesgos','Definir niveles aceptables de riesgo',1),
('5.31','Gestión de riesgos de activos','Aplicar gestión de riesgos a activos',1),
('5.32','Gestión de riesgos de acceso','Aplicar gestión de riesgos a accesos',1),
('5.33','Gestión de riesgos de proveedores','Evaluar y gestionar riesgos de proveedores',1),
('5.34','Gestión de servicios de proveedores','Establecer requisitos de seguridad a proveedores',1),
('5.35','Acuerdos de nivel de servicio (SLA) con proveedores','Incluir seguridad en contratos',1),
('5.36','Gestión de la información de clientes','Proteger información de clientes',1),
('5.37','Gestión de la privacidad y protección de datos personales','Cumplir normativas de privacidad',1),

-- DOMINIO 6 – Personas (8 controles)
('6.1','Política de recursos humanos','Establecer políticas de seguridad para personal',2),
('6.2','Verificación de antecedentes','Verificar antecedentes del personal',2),
('6.3','Términos y condiciones de empleo','Incluir seguridad en contratos laborales',2),
('6.4','Concienciación, educación y formación en seguridad de la información','Capacitar al personal en seguridad',2),
('6.5','Proceso disciplinario','Establecer sanciones por incumplimiento',2),
('6.6','Responsabilidades posteriores al empleo','Gestionar retorno de activos al finalizar empleo',2),
('6.7','Gestión de cambios de responsabilidades','Administrar cambios de rol del personal',2),
('6.8','Confidencialidad o acuerdos de no divulgación','Obligar confidencialidad al personal',2),

-- DOMINIO 7 – Físicos (14 controles)
('7.1','Política de seguridad física','Definir políticas de seguridad física',3),
('7.2','Perímetros físicos','Establecer perímetros seguros',3),
('7.3','Oficinas, salas y instalaciones','Proteger áreas de trabajo',3),
('7.4','Monitoreo físico','Supervisar acceso físico',3),
('7.5','Protección contra amenazas físicas y ambientales','Proteger contra desastres naturales',3),
('7.6','Trabajo en áreas seguras','Establecer áreas de trabajo seguras',3),
('7.7','Escritorio limpio y política de pantalla limpia','Evitar visualización no autorizada',3),
('7.8','Almacenamiento de activos','Almacenar activos de forma segura',3),
('7.9','Instalaciones y equipos de soporte','Proteger equipos de soporte',3),
('7.10','Mantenimiento de equipos','Mantener equipos de forma segura',3),
('7.11','Gestión segura de activos','Asegurar ciclo de vida de activos físicos',3),
('7.12','Equipos y activos de información','Proteger equipos de información',3),
('7.13','Gestión de medios reutilizables','Asegurar borrado de medios reutilizables',3),
('7.14','Gestión de activos fuera de las instalaciones','Proteger activos fuera de las instalaciones',3),

-- DOMINIO 8 – Tecnológicos (34 controles)
('8.1','Política de uso de activos de red','Definir políticas de uso de redes',4),
('8.2','Controles de acceso a redes','Restringir acceso a redes',4),
('8.3','Gestión de servicios de red','Gestionar servicios de red seguros',4),
('8.4','Seguridad de la información en redes','Proteger información en redes',4),
('8.5','Gestión de redes','Gestionar redes de forma segura',4),
('8.6','Controles de puntos finales de red','Proteger puntos finales de red',4),
('8.7','Gestión de servicios de Internet','Controlar uso de servicios de Internet',4),
('8.8','Gestión de información en aplicaciones','Asegurar información en aplicaciones',4),
('8.9','Pruebas de seguridad de aplicaciones','Probar seguridad de aplicaciones',4),
('8.10','Gestión de datos de prueba','Proteger datos de prueba',4),
('8.11','Gestión de código fuente','Proteger código fuente de aplicaciones',4),
('8.12','Gestión de cambios','Controlar cambios en sistemas',4),
('8.13','Gestión de capacidades técnicas','Planificar capacidades de sistemas',4),
('8.14','Gestión de la información restringida','Proteger información restringida',4),
('8.15','Gestión de acceso a la información','Controlar acceso a información',4),
('8.16','Gestión de la información de acceso público','Proteger información pública',4),
('8.17','Gestión de la información de la organización','Gestionar información de la organización',4),
('8.18','Gestión de la información de clientes','Proteger información de clientes',4),
('8.19','Gestión de la información de propiedad intelectual','Proteger propiedad intelectual',4),
('8.20','Gestión de la información de terceros','Proteger información de terceros',4),
('8.21','Gestión de la información de proveedores','Proteger información de proveedores',4),
('8.22','Gestión de la información de usuarios','Proteger información de usuarios',4),
('8.23','Gestión de la información de empleados','Proteger información de empleados',4),
('8.24','Gestión de la información de contratistas','Proteger información de contratistas',4),
('8.25','Gestión de la información de socios','Proteger información de socios',4),
('8.26','Gestión de la información de accionistas','Proteger información de accionistas',4),
('8.27','Gestión de la información de la comunidad','Proteger información de la comunidad',4),
('8.28','Gestión de la información del gobierno','Proteger información del gobierno',4),
('8.29','Gestión de la información de reguladores','Proteger información de reguladores',4),
('8.30','Gestión de la información de auditores','Proteger información de auditores',4),
('8.31','Gestión de la información de acreedores','Proteger información de acreedores',4),
('8.32','Gestión de la información de deudores','Proteger información de deudores',4),
('8.33','Gestión de la información de inversionistas','Proteger información de inversionistas',4),
('8.34','Gestión de la información de otros stakeholders','Proteger información de otros stakeholders',4);
