-- Seed Completo: 93 Controles ISO 27001:2022

-- Primero limpiamos los controles existentes
DELETE FROM controles;

-- A.5: CONTROLES ORGANIZACIONALES (37 controles)
INSERT INTO controles (dominio_id, codigo, nombre, descripcion, objetivo) VALUES
(1, 'A.5.1', 'Políticas de seguridad de la información', 'Políticas para la seguridad de la información definidas, aprobadas, publicadas y comunicadas', 'Proporcionar dirección y apoyo de la gestión'),
(1, 'A.5.2', 'Roles y responsabilidades de seguridad de la información', 'Roles y responsabilidades definidos y asignados', 'Establecer responsabilidades claras'),
(1, 'A.5.3', 'Segregación de funciones', 'Funciones en conflicto segregadas', 'Reducir oportunidades de uso indebido'),
(1, 'A.5.4', 'Responsabilidades de la dirección', 'La dirección requiere que personal aplique seguridad', 'Asegurar cumplimiento de políticas'),
(1, 'A.5.5', 'Contacto con autoridades', 'Contactos apropiados con autoridades mantenidos', 'Facilitar gestión de incidentes'),
(1, 'A.5.6', 'Contacto con grupos de interés especial', 'Contactos con grupos y foros de seguridad mantenidos', 'Acceso a conocimiento especializado'),
(1, 'A.5.7', 'Inteligencia de amenazas', 'Información sobre amenazas recopilada y analizada', 'Conciencia de amenazas de seguridad'),
(1, 'A.5.8', 'Seguridad de la información en la gestión de proyectos', 'Seguridad integrada en gestión de proyectos', 'Seguridad abordada en proyectos'),
(1, 'A.5.9', 'Inventario de información y otros activos', 'Inventario de activos desarrollado y mantenido', 'Identificar activos de información'),
(1, 'A.5.10', 'Uso aceptable de información y otros activos', 'Reglas de uso aceptable identificadas y documentadas', 'Prevenir uso indebido de activos'),
(1, 'A.5.11', 'Devolución de activos', 'Personal devuelve activos al terminar empleo', 'Proteger activos tras terminación'),
(1, 'A.5.12', 'Clasificación de la información', 'Información clasificada según importancia', 'Asegurar protección apropiada'),
(1, 'A.5.13', 'Etiquetado de información', 'Información etiquetada según esquema de clasificación', 'Identificar requisitos de protección'),
(1, 'A.5.14', 'Transferencia de información', 'Reglas de transferencia para proteger información', 'Mantener seguridad durante transferencia'),
(1, 'A.5.15', 'Control de acceso', 'Reglas de control de acceso establecidas', 'Limitar acceso a información'),
(1, 'A.5.16', 'Gestión de identidades', 'Gestión del ciclo de vida de identidades', 'Gestionar identidades de usuarios'),
(1, 'A.5.17', 'Información de autenticación', 'Asignación de información de autenticación controlada', 'Prevenir acceso no autorizado'),
(1, 'A.5.18', 'Derechos de acceso', 'Derechos de acceso provisionados según política', 'Implementar control de acceso'),
(1, 'A.5.19', 'Seguridad de la información en las relaciones con proveedores', 'Procesos y procedimientos para gestión de proveedores', 'Mantener seguridad con proveedores'),
(1, 'A.5.20', 'Abordar la seguridad en acuerdos con proveedores', 'Requisitos de seguridad establecidos con proveedores', 'Mitigar riesgos con proveedores'),
(1, 'A.5.21', 'Gestión de seguridad de la información en la cadena de suministro de TIC', 'Procesos y procedimientos para gestionar riesgos de cadena', 'Asegurar proveedores abordan seguridad'),
(1, 'A.5.22', 'Monitoreo, revisión y gestión de cambios de servicios de proveedores', 'Servicios de proveedores monitoreados regularmente', 'Mantener nivel acordado de seguridad'),
(1, 'A.5.23', 'Seguridad de la información para uso de servicios en la nube', 'Procesos de adquisición, uso y gestión de servicios en nube', 'Establecer responsabilidades de seguridad'),
(1, 'A.5.24', 'Planificación y preparación de la gestión de incidentes', 'Organización planifica respuesta a incidentes', 'Responder rápida y efectivamente'),
(1, 'A.5.25', 'Evaluación y decisión sobre eventos de seguridad', 'Eventos evaluados y clasificados como incidentes', 'Asegurar categorización correcta'),
(1, 'A.5.26', 'Respuesta a incidentes de seguridad', 'Incidentes respondidos según procedimientos', 'Minimizar impacto de incidentes'),
(1, 'A.5.27', 'Aprendizaje de los incidentes de seguridad', 'Conocimiento de incidentes usado para fortalecer seguridad', 'Prevenir recurrencia'),
(1, 'A.5.28', 'Recopilación de evidencia', 'Procedimientos para identificación y recopilación de evidencia', 'Cumplir requisitos legales'),
(1, 'A.5.29', 'Seguridad de la información durante interrupciones', 'Planificación para mantener seguridad durante interrupciones', 'Mantener disponibilidad apropiada'),
(1, 'A.5.30', 'Preparación de las TIC para la continuidad del negocio', 'Preparación de TIC planificada e implementada', 'Asegurar disponibilidad de TIC'),
(1, 'A.5.31', 'Requisitos legales, estatutarios, reglamentarios y contractuales', 'Requisitos identificados y documentados', 'Evitar incumplimientos'),
(1, 'A.5.32', 'Derechos de propiedad intelectual', 'Procedimientos para proteger propiedad intelectual', 'Cumplir requisitos legales'),
(1, 'A.5.33', 'Protección de registros', 'Registros protegidos contra pérdida y alteración', 'Apoyar requisitos legales'),
(1, 'A.5.34', 'Privacidad y protección de información personal identificable', 'Privacidad y PII protegida según requisitos', 'Cumplir requisitos de privacidad'),
(1, 'A.5.35', 'Revisión independiente de la seguridad de la información', 'Enfoque de gestión de seguridad revisado independientemente', 'Asegurar idoneidad continua'),
(1, 'A.5.36', 'Cumplimiento de políticas, reglas y normas', 'Cumplimiento revisado regularmente', 'Asegurar conformidad'),
(1, 'A.5.37', 'Procedimientos operativos documentados', 'Procedimientos documentados y disponibles', 'Asegurar operación correcta');

-- A.6: CONTROLES DE PERSONAS (8 controles)
INSERT INTO controles (dominio_id, codigo, nombre, descripcion, objetivo) VALUES
(2, 'A.6.1', 'Selección', 'Verificación de antecedentes en candidatos', 'Verificar confiabilidad de candidatos'),
(2, 'A.6.2', 'Términos y condiciones de empleo', 'Términos contractuales establecen responsabilidades', 'Asegurar comprensión de responsabilidades'),
(2, 'A.6.3', 'Concienciación, educación y capacitación en seguridad de la información', 'Personal capacitado en políticas de seguridad', 'Mejorar conciencia de seguridad'),
(2, 'A.6.4', 'Proceso disciplinario', 'Proceso formal para violaciones de seguridad', 'Disuadir violaciones'),
(2, 'A.6.5', 'Responsabilidades tras la terminación o cambio de empleo', 'Responsabilidades que permanecen después del empleo', 'Proteger intereses de organización'),
(2, 'A.6.6', 'Acuerdos de confidencialidad o no divulgación', 'Acuerdos que reflejan necesidades de protección', 'Proteger información confidencial'),
(2, 'A.6.7', 'Trabajo remoto', 'Medidas de seguridad implementadas para trabajo remoto', 'Proteger información accedida remotamente'),
(2, 'A.6.8', 'Notificación de eventos de seguridad de la información', 'Personal informa eventos observados', 'Asegurar notificación oportuna');

-- A.7: CONTROLES FÍSICOS (14 controles)
INSERT INTO controles (dominio_id, codigo, nombre, descripcion, objetivo) VALUES
(3, 'A.7.1', 'Perímetros de seguridad física', 'Perímetros definidos para proteger áreas', 'Prevenir acceso físico no autorizado'),
(3, 'A.7.2', 'Entrada física', 'Áreas seguras protegidas con controles de entrada', 'Asegurar solo personal autorizado acceda'),
(3, 'A.7.3', 'Seguridad de oficinas, despachos e instalaciones', 'Seguridad física diseñada para oficinas', 'Prevenir acceso no autorizado'),
(3, 'A.7.4', 'Monitoreo de seguridad física', 'Instalaciones monitoreadas continuamente', 'Detectar y disuadir acceso no autorizado'),
(3, 'A.7.5', 'Protección contra amenazas físicas y ambientales', 'Protección contra amenazas físicas y ambientales', 'Prevenir daño a activos'),
(3, 'A.7.6', 'Trabajo en áreas seguras', 'Medidas de seguridad para trabajo en áreas seguras', 'Mejorar seguridad en áreas seguras'),
(3, 'A.7.7', 'Escritorio y pantalla limpios', 'Reglas de escritorio limpio y pantalla limpia', 'Reducir riesgo de acceso no autorizado'),
(3, 'A.7.8', 'Ubicación y protección de equipos', 'Equipos ubicados y protegidos adecuadamente', 'Reducir riesgos ambientales'),
(3, 'A.7.9', 'Seguridad de los activos fuera de las instalaciones', 'Activos fuera de instalaciones protegidos', 'Prevenir pérdida o compromiso'),
(3, 'A.7.10', 'Medios de almacenamiento', 'Medios de almacenamiento gestionados según clasificación', 'Prevenir divulgación no autorizada'),
(3, 'A.7.11', 'Servicios de soporte', 'Servicios de soporte mantenidos según requisitos', 'Asegurar disponibilidad continua'),
(3, 'A.7.12', 'Seguridad del cableado', 'Cables protegidos contra interceptación', 'Prevenir acceso no autorizado'),
(3, 'A.7.13', 'Mantenimiento de equipos', 'Equipos mantenidos según intervalos especificados', 'Asegurar disponibilidad continua'),
(3, 'A.7.14', 'Eliminación o reutilización segura de equipos', 'Equipos verificados antes de eliminación', 'Prevenir fuga de información');

-- A.8: CONTROLES TECNOLÓGICOS (34 controles)
INSERT INTO controles (dominio_id, codigo, nombre, descripcion, objetivo) VALUES
(4, 'A.8.1', 'Dispositivos de punto final de usuario', 'Información en dispositivos protegida', 'Proteger información en dispositivos'),
(4, 'A.8.2', 'Derechos de acceso privilegiados', 'Asignación de derechos privilegiados restringida', 'Prevenir acceso no autorizado'),
(4, 'A.8.3', 'Restricción de acceso a la información', 'Acceso restringido según política', 'Asegurar acceso autorizado solamente'),
(4, 'A.8.4', 'Acceso al código fuente', 'Acceso de lectura y escritura controlado', 'Prevenir introducción no autorizada'),
(4, 'A.8.5', 'Autenticación segura', 'Tecnologías de autenticación segura implementadas', 'Asegurar identidad de usuarios'),
(4, 'A.8.6', 'Gestión de capacidad', 'Uso de recursos monitoreado y proyecciones realizadas', 'Asegurar desempeño requerido'),
(4, 'A.8.7', 'Protección contra malware', 'Protección contra malware implementada', 'Proteger contra malware'),
(4, 'A.8.8', 'Gestión de vulnerabilidades técnicas', 'Información sobre vulnerabilidades obtenida', 'Prevenir explotación'),
(4, 'A.8.9', 'Gestión de configuración', 'Configuraciones de seguridad establecidas', 'Asegurar consistencia de seguridad'),
(4, 'A.8.10', 'Eliminación de información', 'Información eliminada cuando no es requerida', 'Prevenir divulgación innecesaria'),
(4, 'A.8.11', 'Enmascaramiento de datos', 'Enmascaramiento usado según política', 'Limitar exposición de datos sensibles'),
(4, 'A.8.12', 'Prevención de fuga de datos', 'Medidas de prevención de fuga aplicadas', 'Detectar y prevenir divulgación'),
(4, 'A.8.13', 'Respaldo de información', 'Copias de respaldo mantenidas según política', 'Asegurar disponibilidad'),
(4, 'A.8.14', 'Redundancia de instalaciones de procesamiento de información', 'Instalaciones implementadas con redundancia', 'Asegurar disponibilidad'),
(4, 'A.8.15', 'Registro', 'Registros que documentan actividades producidos', 'Detectar actividades no autorizadas'),
(4, 'A.8.16', 'Actividades de monitoreo', 'Redes y sistemas monitoreados', 'Detectar comportamiento anómalo'),
(4, 'A.8.17', 'Sincronización de reloj', 'Relojes de sistemas sincronizados', 'Asegurar exactitud de registros'),
(4, 'A.8.18', 'Uso de programas de utilidad privilegiados', 'Uso de programas privilegiados restringido', 'Prevenir anulación de controles'),
(4, 'A.8.19', 'Instalación de software en sistemas operativos', 'Procedimientos e implementación de software controlados', 'Prevenir introducción de vulnerabilidades'),
(4, 'A.8.20', 'Seguridad de redes', 'Redes, dispositivos y servicios gestionados', 'Proteger información en redes'),
(4, 'A.8.21', 'Seguridad de servicios de red', 'Mecanismos de seguridad identificados e implementados', 'Mantener seguridad de servicios'),
(4, 'A.8.22', 'Segregación de redes', 'Grupos de servicios segregados en redes', 'Prevenir acceso no autorizado'),
(4, 'A.8.23', 'Filtrado web', 'Acceso a sitios web externos gestionado', 'Prevenir acceso a contenido malicioso'),
(4, 'A.8.24', 'Uso de criptografía', 'Reglas para uso de criptografía definidas', 'Asegurar uso apropiado'),
(4, 'A.8.25', 'Ciclo de vida de desarrollo seguro', 'Reglas para desarrollo seguro establecidas', 'Asegurar seguridad de aplicaciones'),
(4, 'A.8.26', 'Requisitos de seguridad de las aplicaciones', 'Requisitos de seguridad identificados', 'Asegurar seguridad en aplicaciones'),
(4, 'A.8.27', 'Principios de ingeniería y arquitectura de sistemas seguros', 'Principios de diseño seguro establecidos', 'Asegurar seguridad en diseño'),
(4, 'A.8.28', 'Codificación segura', 'Principios de codificación segura aplicados', 'Prevenir vulnerabilidades en software'),
(4, 'A.8.29', 'Pruebas de seguridad en desarrollo y aceptación', 'Procesos de pruebas de seguridad definidos', 'Verificar requisitos de seguridad'),
(4, 'A.8.30', 'Desarrollo externalizado', 'Organización supervisa desarrollo externalizado', 'Asegurar seguridad en desarrollo externo'),
(4, 'A.8.31', 'Separación de entornos de desarrollo, pruebas y producción', 'Entornos separados y protegidos', 'Reducir riesgo de acceso no autorizado'),
(4, 'A.8.32', 'Gestión de cambios', 'Cambios a instalaciones y sistemas controlados', 'Prevenir interrupciones'),
(4, 'A.8.33', 'Información de prueba', 'Datos de prueba seleccionados y protegidos', 'Proteger información operacional'),
(4, 'A.8.34', 'Protección de sistemas de información durante las pruebas de auditoría', 'Pruebas de auditoría planificadas y acordadas', 'Minimizar impacto en operaciones');
